[package]
name = "the_vault"
version = "1.0.0"
authors = []

[addresses]
vault = "_"

[dev-addresses]
vault = "0x123"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
